services:
  mongo:
    container_name: mongo
    image: mongo:8.0-rc
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - .:/json
      - mongodbdata:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  exist:
    image: existdb/existdb:5.0.0-RC8
    container_name: exist
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - .:/xml
      - existdbdata:/data/db

  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"

    volumes:
      - neo4jdata:/data

  postgresXML:
    container_name: postgresXML
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - postgresxmldata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=root

  postgresJSON:
    container_name: postgresJSON
    image: postgres:alpine
    ports:
      - "5433:5433"
    volumes:
      - postgresjsondata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=root

volumes:
  mongodbdata:
  existdbdata:
  neo4jdata:
  postgresxmldata:
  postgresjsondata:
